x-logging:
  logging: &default-logging
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

networks:
  internal:
    driver: bridge

volumes:
  minio-data-prod:
  valkey-data-prod:

services:
  app:
    stdin_open: true
    tty: true
    build: .
    image: lbstudio:latest
    restart: unless-stopped
    user: "1001:1001"
    networks:
      - internal
    ports:
      - "8080:8080"
    env_file:
      - .env.list
    volumes:
      - ${PWD}/mydata:/label-studio/data:rw
    depends_on:
      - minio
      - redis
    command: label-studio-daphne

  worker-low:
    image: lbstudio:latest
    restart: unless-stopped
    user: "1001:1001"
    networks:
      - internal
    depends_on:
      - app
      - redis
    env_file:
      - .env.list
    volumes:
      - ${PWD}/mydata:/label-studio/data:rw
    command: python label_studio/manage.py rqworker low

  worker-default:
    image: lbstudio:latest
    restart: unless-stopped
    user: "1001:1001"
    networks:
      - internal
    depends_on:
      - app
      - redis
    env_file:
      - .env.list
    volumes:
      - ${PWD}/mydata:/label-studio/data:rw
    command: python label_studio/manage.py rqworker default

  worker-high:
    image: lbstudio:latest
    restart: unless-stopped
    user: "1001:1001"
    networks:
      - internal
    depends_on:
      - app
      - redis
    deploy:
      replicas: 2
    env_file:
      - .env.list
    volumes:
      - ${PWD}/mydata:/label-studio/data:rw
    command: python3 label_studio/manage.py rqworker high

  worker-critical:
    image: lbstudio:latest
    restart: unless-stopped
    user: "1001:1001"
    networks:
      - internal
    deploy:
      replicas: 2
    depends_on:
      - app
      - redis
    env_file:
      - .env.list
    volumes:
      - ${PWD}/mydata:/label-studio/data:rw
    command: python3 label_studio/manage.py rqworker critical

  minio:
    image: "minio/minio:${MINIO_VERSION:-RELEASE.2025-04-22T22-12-26Z}"
    command: server /data --console-address ":9009"
    restart: unless-stopped
    logging: *default-logging
    env_file:
      - .env.list
    ports:
      - "127.0.0.1:9009:9009"
    volumes:
      - minio-data-prod:/data
    networks:
      - internal

  redis:
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - valkey-data-prod:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
